export interface Contact {
  id?: string // optional because it's generated by the server
  contactListId: string
  firstName: string
  lastName: string
  preferredName: string
  email: string
  phone: string
  fax: string
  addressId: string
  doNotContact: boolean
}
